### ISSUE TITLE
Mod breaks vanilla priority input

### ISSUE THREAD

**Issue by ghost** [GreyHak/dsp-smooth-splitter#1]
Enabling the mod causes splitters to ignore priority input.

https://user-images.githubusercontent.com/4206605/115317694-5d922a00-a139-11eb-85a7-1e6e067ae0a9.mp4

https://user-images.githubusercontent.com/4206605/115317705-6420a180-a139-11eb-9a42-088d789975ae.mp4

**Comment by GreyHak** [comment]
@helium2s1 Thank you for the report, and my apologies for taking way too long to respond.  My mod does not touch anything related to inputs.  So it can't be messing up priorities.  Here's what I believe you're observing.  The smoothing function works by pushing elements into available output empty space.  So it effectively speeds up the output belt.  It has a range of about 10 belt-lengths on the output.  So you could consider the belt speed for the 10 belts on the output to be very fast.  Practically the only limit is a result of the 11th belt.  So if the belt length is less than 11, it will move as fast as the receiving machine will take the items in.
I love the videos you've posted.  They helped a lot, together with my own testing, to understand the issue you were bringing up.

**Comment by GreyHak** [comment]
@helium2s1 The issue has been fixed in v1.0.2.  Thank you again for the report.
